Conflict status when saving data in a profile.
saveourtool/save-cloud pull request #1428
Opened 2022-11-09 16:08 UTC by Cheshiriks

Fixed bug updating user

Close #1412

2022-11-09 16:28 UTC, sanyavertolet approved these changes

2022-11-10 04:42 UTC, petertrr requested changes
Please add a unit test for this logic, since it's getting more complicated and there are three branches already. Also, in which case will `user.name` be `null`?

2022-11-10 10:12 UTC, Cheshiriks commented
> Please add a unit test for this logic, since it's getting more complicated and there are three branches already. Also, in which case will `user.name` be `null`?

Added tests.
There is a check for null at a higher level, so it is not needed here.

2022-11-10 13:27 UTC, petertrr approved these changes

2022-11-10 13:43 UTC, merged