User length name
saveourtool/save-cloud pull request #2410
Opened 2023-08-03 16:21 UTC by Cheshiriks

User length name

2023-08-03 21:34 UTC, sanyavertolet requested changes

2023-08-03 21:34 UTC, sanyavertolet commented on save-backend/src/main/kotlin/com/saveourtool/save/backend/controllers/UsersDetailsController.kt
> +                .filter { newUserInfo.name.length <= 22 }
**Must** be moved to `const val`

Or even reuse `isValidName`

2023-08-03 21:34 UTC, sanyavertolet commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/inputform/InputForms.kt
> +private const val NAME_ORG_PROJECT_TOOLTIP = "Name must not be longer than 22 characters." +
22 should be extracted

2023-08-03 21:34 UTC, sanyavertolet commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreateOrganizationView.kt
> +                                                    state.organizationDto.name.length <= 22) && state.conflictErrorMessage == null
Must be moved to const val

2023-08-04 07:26 UTC, akuleshov7 approved these changes

2023-08-04 07:27 UTC, merged

2023-08-04 09:14 UTC, nulls commented
do we need a separate PR for `val 22`?

2023-08-04 09:16 UTC, sanyavertolet commented
> do we need a separate PR for `val 22`?

not sure about separate PR, but it definitely should be fixed