Correct filter in ExecutionView.kt
saveourtool/save-cloud pull request #892
Opened 2022-07-08 13:50 UTC by Arrgentum

## Whats Added:
* Filter value status and testSuite now changes the values of the output table data
* Safe value status and testSuite for future use
* Some corrected README.md

## Issue(first part #838)

2022-07-08 14:28 UTC, sanyavertolet approved these changes
lgtm

2022-07-08 14:37 UTC, petertrr requested changes
See comment above

2022-07-08 14:41 UTC, Arrgentum commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
> +    var status: TestResultStatus?
If I understand correctly, then status and testSuite are property in tableProps

2022-07-08 14:52 UTC, petertrr commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/tables/TableComponent.kt
> +    var status: TestResultStatus?
Ok, we'll need a way to inherit `TableProps` and override dependencies, if needed

2022-07-12 13:11 UTC, petertrr approved these changes

2022-07-12 14:10 UTC, merged