Say no to legacy react wrappers
saveourtool/save-cloud pull request #899
Opened 2022-07-11 12:36 UTC by sanyavertolet

### What's done:
 - [x] Moved all `fc`s to `FC`s
 - [ ] Partly moved all `RComponent`s to `Component`s

2022-07-11 14:49 UTC, petertrr requested changes
Since the proposed change is too large, I suggest to split it into two parts: right now we can merge `fc -> FC` migration and add `fc` into Detekt's forbidden list (`ForbiddenMethodCall`, `ForbiddenImport` and similar rules), and then we can migrate class components

2022-07-11 14:49 UTC, petertrr commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/modal/Modal.kt
> +@Deprecated("Use non-legacy code")
I believe in this PR we'll need to completely remove dependency on `-legacy` artifact, if it's possible :)

2022-07-11 14:49 UTC, petertrr commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/externals/chart/PieChartBuilder.kt
> +) = PieChart::class.react.create {
I don't think it should be `create`, but rather extension `ElemenType.invoke` from `ChildrenBuilder` should be used

2022-07-11 14:49 UTC, petertrr commented on save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/views/CreateOrganizationView.kt
> +                                            changeFields(InputTypes.ORGANIZATION_NAME, it as Event)
What is the inferred type of `it` here?

2022-07-14 08:33 UTC, sanyavertolet commented
As far as this PR was split into two different (#907 and #913), it should be considered as done.

2022-07-14 08:33 UTC, closed without merging